package Presentacion;

import Dominio.Usuario;
import Dominio.ConjuntoUsuarios;
import Presentacion.CtrlPresentacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Paola
 */
public class VistaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuarios
     */
    
    private CtrlPresentacion cp;
    public VistaUsuarios(CtrlPresentacion cp) {
        initComponents();
       
        this.cp = cp;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonUsuarioPriv = new javax.swing.JButton();
        jButtonUsuarioNoPriv = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUsuarioPriv.setBackground(new java.awt.Color(0, 204, 204));
        jButtonUsuarioPriv.setFont(new java.awt.Font("Retro Computer", 3, 36)); // NOI18N
        jButtonUsuarioPriv.setText("USUARIO");
        jButtonUsuarioPriv.setBorderPainted(false);
        jButtonUsuarioPriv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioPrivActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUsuarioPriv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 330, 120));

        jButtonUsuarioNoPriv.setBackground(new java.awt.Color(0, 204, 204));
        jButtonUsuarioNoPriv.setFont(new java.awt.Font("Retro Computer", 3, 36)); // NOI18N
        jButtonUsuarioNoPriv.setText("VISITANTE");
        jButtonUsuarioNoPriv.setBorderPainted(false);
        jButtonUsuarioNoPriv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioNoPrivActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUsuarioNoPriv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 330, 120));

        jButton1.setFont(new java.awt.Font("Retro Computer", 0, 13)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsuarioPrivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioPrivActionPerformed
        //this.cp.vistaUsuarioPriv();
        dispose();
    }//GEN-LAST:event_jButtonUsuarioPrivActionPerformed

    private void jButtonUsuarioNoPrivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioNoPrivActionPerformed
        //this.cp.vistaUsuarioNoPriv();
        dispose();
           
    }//GEN-LAST:event_jButtonUsuarioNoPrivActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.cp.controlaVistas("Principal");
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
                                               

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonUsuarioNoPriv;
    private javax.swing.JButton jButtonUsuarioPriv;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
